//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionGrafos.Transaction.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dir_Palabras
    {
        public int id { get; set; }
        public string Palabra { get; set; }
        public int Cant_Letras { get; set; }
    }
}
